services:

  traefik:
    image: "traefik:v2.4"
    networks: 
      - traefik_net
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  
  comment-service:
    image: comment-service
    restart: always
    networks: 
      - traefik_net
      - database
      - rabbitmq
    depends_on: 
      - auth-service
      - mongo-config
      - rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docker_traefik_net"
      - "traefik.http.services.comment-service.loadbalancer.server.port=80"
      - "traefik.http.routers.comment-service.rule=Host(`comment.localhost`) && PathPrefix(`/comment`)"
      - "traefik.http.routers.comment-service.middlewares=auth-service"
      - "traefik.http.routers.comment-service.entrypoints=web"

  auth-service:
    image: auth-service
    restart: always
    networks:
      - traefik_net
      - database
      - rabbitmq
    depends_on:
      - mongo-config
      - rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docker_traefik_net"
      - "traefik.http.middlewares.auth-service.forwardauth.address=http://auth-service:80/auth/"
      - "traefik.http.middlewares.auth-service.forwardauth.authResponseHeaders=x-user-id"
      - "traefik.http.middlewares.auth-service.forwardauth.authRequestHeaders=x-auth-token"
      - "traefik.http.middlewares.auth-service.forwardauth.trustForwardHeader=true"
      - "traefik.http.services.auth-service.loadbalancer.server.port=80"
      - "traefik.http.routers.auth-service.rule=Host(`auth.localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-service.entrypoints=web"

  mongodb:
    image: mongo
    command: mongod --replSet  rs0 --dbpath ./data/db --oplogSize 16 
    networks: 
      - database
    volumes:
      - ./mongo/data1/db:/data/db # This is where your volume will persist. e.g. VOLUME-DIR = ./volumes/mongodb
      - ./mongo/data1/configdb:/data/configdb
    restart: always

  mongo2:
    image: mongo
    command: mongod --replSet  rs0 --dbpath ./data/db --oplogSize 16 
    networks: 
      - database
    volumes:
      - ./mongo/data2/db:/data/db # This is where your volume will persist. e.g. VOLUME-DIR = ./volumes/mongodb
      - ./mongo/data2/configdb:/data/configdb
    restart: always

  mongo3:
    image: mongo
    command: mongod --replSet rs0 --dbpath ./data/db  --oplogSize 16 
    networks:
      - database
    volumes:
      - ./mongo/data3/db:/data/db # This is where your volume will persist. e.g. VOLUME-DIR = ./volumes/mongodb
      - ./mongo/data3/configdb:/data/configdb
    restart: always

  mongo-config:
    image: mongo
    depends_on:
      - mongodb
      - mongo2
      - mongo3
    networks:
      - database
    volumes:
      - ./scripts:/scripts
    entrypoint: ['/scripts/setup.sh']

  rabbitmq:
    image: rabbitmq
    networks: 
    - rabbitmq
      
networks:
  traefik_net:
    driver: bridge
  database:
    driver: bridge
  rabbitmq:
    driver: bridge